[package]
name = "misy-tui"
version.workspace = true
edition.workspace = true

[[bin]]
name = "misy"
path = "src/main.rs"

[dependencies]
arboard = { workspace = true, features = ["image-data"] }
base64.workspace = true
crossterm.workspace = true
misy-core = { path = "../misy-core" }
ratatui.workspace = true
serde.workspace = true
serde_json.workspace = true
unicode-width.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
